fn main() {
  // Register the app's own commands in the ACL so the page (served from
  // `http://localhost:<port>`, a remote origin) can invoke them. Without this
  // the app manifest is empty and remote-origin invokes are rejected with
  // "not allowed by ACL". Each command gets an autogenerated
  // `allow-<command>` permission referenced from capabilities/default.json.
  let app_manifest = tauri_build::AppManifest::new().commands(&[
    "ensure_bridge",
    "restart_bridge",
    "bridge_health",
    "bridge_get_chats",
    "bridge_get_messages",
    "bridge_send_message",
    "bridge_refresh",
    "bridge_mark_seen",
    "bridge_delete_chat",
    "bridge_archive_chat",
    "bridge_unarchive_chat",
    "bridge_send_audio",
    "bridge_send_image",
    "bridge_send_media",
    "bridge_edit_message",
    "bridge_delete_message",
    "bridge_react_message",
    "bridge_get_link_preview",
    "bridge_forward_message",
    "bridge_get_media",
    "bridge_get_profile_pic",
    "open_url",
    "open_media_external",
    "get_pending_deep_link",
    "log_debug",
    "get_process_stats",
    "hide_quick_cmd",
  ]);

  tauri_build::try_build(
    tauri_build::Attributes::new().app_manifest(app_manifest),
  )
  .expect("error while running tauri-build");
}
